name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch matplotlib torchvision pytest

    #- name: Test with unittest
    #  run: |
    #    python S16/test_cases.py

    - name: Test with unittest S5 - 1
      run: |
        python S5/test.py

